settings:
    source: 'BFDemoBundle:Contact'
    type: object
    condition: my_messages
    ref: name
    columns:
        id:
            label: ID
            type: String
        name:
            label: null
            type: string
        email:
            label: null
            type: string
#            hidden: true
