metadata:
  name: poster_message_type
  fields:
    to:
      widget:
        choice:
          choices: {user: user, admin: admin}
    subject:
      widget:
        text: ~
    content:
      widget:
        textarea: ~