bf_demo:
    pattern:  /
    defaults: { _controller: BFDemoBundle:Demo:index }

bf_demo_contact:
    pattern:  /contact
    defaults: { _controller: BFDemoBundle:Demo:contact }

    

bf_demo_lister_contact:
    pattern:  /contacts
    defaults: { _controller: BFDemoBundle:Demo:listerContacts }

    