bf_demo_login:
    pattern:  /login
    defaults: { _controller: BFDemoBundle:Secured:login }

bf_security_check:
    pattern:  /login_check
    defaults: { _controller: BFDemoBundle:Secured:securityCheck }

bf_demo_logout:
    pattern:  /logout
    defaults: { _controller: BFDemoBundle:Secured:logout }
