parameters:
    bf.demo.breadcrumb.class: BF13\BusinessApplicationBundle\Service\Breadcrumb\Breadcrumb
    bf.demo.breadcrumb.extension.class: BF13\BusinessApplicationBundle\Service\Breadcrumb\TwigExtension\BreadcrumbExtension

services:
    twig.extension.bf.demo:
      class: BF\DemoBundle\Twig\Extension\DemoExtension
      arguments: [@twig.loader]
      tags:
        - { name: twig.extension }
        
    bf.demo.controller.listener:
      class: BF\DemoBundle\EventListener\ControllerListener
      arguments: [@twig.extension.bf.demo]
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    bf.demo.authentication.listener :
        class: BF\DemoBundle\EventListener\SecurityAuthenticationListener
        arguments: [@bf13.app.notification]
        tags:
          - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthenticationSuccess }
        