parameters:
    bf.demo.breadcrumb.class: BF13\Component\Breadcrumb\Breadcrumb
    bf.demo.breadcrumb.extension.class: BF13\Component\Breadcrumb\TwigExtension\BreadcrumbExtension

services:
    twig.extension.bf.demo:
      class: BF\DemoBundle\Twig\Extension\DemoExtension
      arguments: []
      tags:
        - { name: twig.extension }
        
    bf.demo.authentication.listener :
        class: BF\DemoBundle\EventListener\SecurityAuthenticationListener
        arguments: [@bf13.app.notification]
        tags:
          - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthenticationSuccess }
        